function txt = metrics_to_markdown(metrics)
%METRICS_TO_MARKDOWN Format a metric struct for Markdown output.

txt = sprintf([ ...
    '| 指标 | 数值 |\n', ...
    '|---|---:|\n', ...
    '| theta 调节时间 | %s s |\n', ...
    '| x 调节时间 | %s s |\n', ...
    '| theta 超调量 | %.6g rad |\n', ...
    '| x 超调量 | %.6g m |\n', ...
    '| theta 稳态误差 | %.6g rad |\n', ...
    '| x 稳态误差 | %.6g m |\n', ...
    '| 控制量峰值 | %.6g N |\n', ...
    '| 控制能量 | %.6g |\n', ...
    '| 代价 J | %.6g |\n', ...
    '| Reward | %.6g |\n', ...
    '| 是否失败 | %s |\n'], ...
    finite_num(metrics.thetaSettlingTime), finite_num(metrics.xSettlingTime), ...
    metrics.thetaOvershoot, metrics.xOvershoot, ...
    metrics.thetaSteadyStateError, metrics.xSteadyStateError, ...
    metrics.uPeak, metrics.uEnergy, metrics.costJ, metrics.reward, string(metrics.failed));
end

function s = finite_num(v)
if isinf(v)
    s = 'Inf';
else
    s = sprintf('%.4g', v);
end
end
